---
output:
  pdf_document: default
---
# Exercício 9

Semente: **435**; $m$: **950**; $\mu$: **9.49**; $\sigma$: **1.89**; $(1-\alpha)$: **0.95**

```{r results="hide", error=FALSE, warning=FALSE, message=FALSE}
#bilbiotecas
library(tidyverse)
library(openxlsx)
library(reshape)
```

```{r out.width="70%", fig.align='center'}
set.seed(435)#gerar a distribuição
vetori=NULL
grafico=data.frame()
for(n in seq(100,5000,100)){
  for (i in 1 : 950){
    vetori = c(vetori, 2*qnorm(1-(0.05/2))*(sd(rnorm(n, mean=9.49, sd=1.89))/
                                      sqrt(n)))#amplitude do IC
  }
  #tabela com a primeira coluna sendo a dimensão n e a segunda coluna a média das
  #amplitudes para esse n
  grafico= rbind(grafico, c(n,mean(vetori)))
}
names(grafico)[1] <- 'n'
names(grafico)[2] <- 'media'

ggplot() + 
  geom_point(data=grafico, aes(x=n, y = media))+
  labs(title = "Média da âmplitude dos IC em função de n",x = "n",y="MA")
```

### Conclusão

O valor médio da amplitude dos 950 intervalos de confiança decresce com o aumento da dimensão da amostra. De facto, quando n tende para infinito, o desvio-padrão da amostra torna-se no desvio-padrão da própria população, $\sigma$, e podemos dizer que MA decresce por uma razão $\frac{1}{\sqrt{n}}$.

